name: Main Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-frontend:
    uses: ./.github/workflows/build-service.yaml
    secrets: inherit
    with:
      service-name: frontend
      image-name: registry.humanitec.io/public/bank-demo-frontend
      HUMANITEC_ORG: ${{ vars.HUMANITEC_ORG }}

  build-moneyapi:
    uses: ./.github/workflows/build-service.yaml
    secrets: inherit
    with:
      service-name: money-api
      image-name: registry.humanitec.io/public/bank-demo-money-api
      HUMANITEC_ORG: ${{ vars.HUMANITEC_ORG }}

  build-usersapi:
    uses: ./.github/workflows/build-service.yaml
    secrets: inherit
    with:
      service-name: users-api
      image-name: registry.humanitec.io/public/bank-demo-users-api
      HUMANITEC_ORG: ${{ vars.HUMANITEC_ORG }}

  run-score:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-moneyapi, build-usersapi]

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        name: Check if score files have been updated
        id: changes
        with:
          filters: |
            scorefiles:
              - '**/score.yaml'
              - '**/humanitec.score.yaml'
      
      # Override the image name and tag for services which the version built in previous steps
      - name: Create overrides file
        if: steps.changes.outputs.scorefiles == 'true'
        run: |
          wget -q https://github.com/mikefarah/yq/releases/download/v4.30.8/yq_linux_amd64 -O yq
          chmod +x yq
          mv yq /usr/local/bin

          yq e -n ".containers.frontend.image = \"${{needs.build-frontend.outputs.IMAGE_NAME}}:${{needs.build-frontend.outputs.IMAGE_TAG}}\"" > frontend.overrides.score.yaml
          yq e -n ".containers.moneyapi.image = \"${{needs.build-moneyapi.outputs.IMAGE_NAME}}:${{needs.build-moneyapi.outputs.IMAGE_TAG}}\"" > moneyapi.overrides.score.yaml
          yq e -n ".containers.usersapi.image = \"${{needs.build-usersapi.outputs.IMAGE_NAME}}:${{needs.build-usersapi.outputs.IMAGE_TAG}}\"" > usersapi.overrides.score.yaml
              
      - name: Install score-humanitec
        if: steps.changes.outputs.scorefiles == 'true'
        run: |
          wget https://github.com/score-spec/score-humanitec/releases/download/0.5.0/score-humanitec_0.5.0_linux_amd64.tar.gz
          tar -xvf score-humanitec_0.5.0_linux_amd64.tar.gz
          chmod +x score-humanitec
          mv score-humanitec /usr/local/bin

      - name: Run Score - Money API
        if: steps.changes.outputs.scorefiles == 'true'
        run: score-humanitec delta --retry --deploy --token ${{ secrets.HUMANITEC_TOKEN }} --org ${{ vars.HUMANITEC_ORG }} --app bank-demo --env development -f money-api/score.yaml --overrides moneyapi.overrides.score.yaml
      
      - name: Run Score - Users API
        if: steps.changes.outputs.scorefiles == 'true'
        run: score-humanitec delta --retry --deploy --token ${{ secrets.HUMANITEC_TOKEN }} --org ${{ vars.HUMANITEC_ORG }} --app bank-demo --env development -f users-api/score.yaml --overrides usersapi.overrides.score.yaml

      - name: Run Score - Frontend
        if: steps.changes.outputs.scorefiles == 'true'
        run: score-humanitec delta --retry --deploy --token ${{ secrets.HUMANITEC_TOKEN }} --org ${{ vars.HUMANITEC_ORG }} --app bank-demo --env development -f frontend/score.yaml --extensions frontend/humanitec.score.yaml --overrides frontend.overrides.score.yaml